# Generated by Django 4.2.3 on 2023-08-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='cart_price',
        ),
    ]
