# Generated by Django 4.2.3 on 2023-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_rename_price_cartitem_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
