# Generated by Django 4.2.3 on 2023-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_colour', models.CharField(max_length=50)),
                ('variant_stock', models.IntegerField(default=0)),
                ('variant_price', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('variant_image', models.ImageField(upload_to='variant_image')),
            ],
        ),
    ]
