# Generated by Django 4.2.3 on 2023-08-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_variant_variant'),
        ('category', '0002_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
