# Generated by Django 4.2.3 on 2023-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
