# Generated by Django 4.2.3 on 2023-07-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_variant_variation'),
        ('category', '0004_category_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
