# Generated by Django 4.2.3 on 2023-07-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
