# Generated by Django 4.2.3 on 2023-08-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='product_relation',
        ),
        migrations.AddField(
            model_name='variant',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
