# Generated by Django 4.2.3 on 2023-07-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_variant'),
        ('store', '0002_product_brand_product_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.variant'),
            preserve_default=False,
        ),
    ]
