# Generated by Django 4.2.3 on 2023-08-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_variant_product_relation_variant_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='product_id',
            new_name='product',
        ),
    ]
