# Generated by Django 4.2.3 on 2023-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_id_variant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_price',
            field=models.IntegerField(default=0),
        ),
    ]
