# Generated by Django 4.2.3 on 2023-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_variant_delete_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
