# Generated by Django 4.2.3 on 2023-08-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_variant'),
        ('store', '0007_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.variant'),
        ),
    ]
