# Generated by Django 4.2.3 on 2023-08-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_colour', models.CharField(max_length=50)),
                ('variant_stock', models.IntegerField(default=0)),
                ('variant_price', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('variant_image', models.ImageField(upload_to='variant_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
