# Generated by Django 4.2.3 on 2023-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_wishlist_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='variant_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
