# Generated by Django 4.2.3 on 2023-08-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_line_1',
            field=models.CharField(),
        ),
    ]
