# Generated by Django 4.2.3 on 2023-08-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order_number',
        ),
    ]
