# Generated by Django 4.2.3 on 2023-08-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
