# Generated by Django 4.2.3 on 2023-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_country_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='set_default',
            field=models.BooleanField(default=False),
        ),
    ]
