# Generated by Django 4.2.3 on 2023-08-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Returned', 'Delivered')], default='Ordered', max_length=10),
        ),
    ]
