# Generated by Django 4.2.3 on 2023-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_razorpay_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpay_order',
            old_name='order_id',
            new_name='provider_order_id',
        ),
        migrations.RemoveField(
            model_name='razorpay_order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='razorpay_order',
            name='signature_id',
            field=models.CharField(default=1, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
    ]
