# Generated by Django 4.2.3 on 2023-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_payment_order_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bulk_order_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
