# Generated by Django 4.2.3 on 2023-08-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_bulk_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bulk_order_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
