# Generated by Django 4.2.3 on 2023-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_bulk_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Returned', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=10),
        ),
    ]
