# Generated by Django 4.2.3 on 2023-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.IntegerField(blank=0, default=0, null=0),
            preserve_default=False,
        ),
    ]
