# Generated by Django 4.2.3 on 2023-08-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_coupon'),
        ('orders', '0015_alter_order_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carts.coupon'),
        ),
    ]
