# Generated by Django 4.2.3 on 2023-08-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_coupon'),
        ('orders', '0016_alter_order_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_id',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carts.coupon'),
        ),
    ]
